### ISSUE TITLE
  Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by BrixSat** [dreamdev21/Laravel-Event-management-system#2]
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
Compiling common classes

  [ErrorException]
  Invalid characters passed for attempted conversion, these have been ignored

[2021-04-03 09:49:19] production.ERROR: ErrorException: Invalid characters passed for attempted conversion, these have been ignored in C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php:103
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Invalid charact...', 'C:\\xampp\\htdocs...', 103, Array)
#1 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php(103): hexdec('xC2')
#2 [internal function]: PhpParser\Node\Scalar\String_::PhpParser\Node\Scalar\{closure}(Array)
#3 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php(96): preg_replace_callback('~\\\\([\\\\$nrtfve]...', Object(Closure), '\\xC2\\xA0')
#4 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\String_.php(69): PhpParser\Node\Scalar\String_::parseEscapeSequences('\\xC2\\xA0', '"', true)
#5 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Parser\Php7.php(2381): PhpParser\Node\Scalar\String_::parse('"\\xC2\\xA0"')
#6 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\ParserAbstract.php(247): PhpParser\Parser\Php7->reduceRule395()
#7 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Parser\Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n namespac...')
#8 C:\xampp\htdocs\attendize\vendor\nikic\php-parser\lib\PhpParser\Parser\Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), '<?php\n namespac...')
#9 C:\xampp\htdocs\attendize\vendor\classpreloader\classpreloader\src\ClassPreloader.php(127): PhpParser\Parser\Multiple->parse('<?php\n namespac...')
#10 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php(83): ClassPreloader\ClassPreloader->getCode('C:\\xampp\\htdocs...', false)
#11 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php(64): Illuminate\Foundation\Console\OptimizeCommand->compileClasses()
#12 [internal function]: Illuminate\Foundation\Console\OptimizeCommand->fire()
#13 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#14 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#15 C:\xampp\htdocs\attendize\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\attendize\vendor\symfony\console\Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\attendize\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\OptimizeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\attendize\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\attendize\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\attendize\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by edocollado** [comment]
Can you solve this problem?

**Comment by abhyudayasrinet** [comment]
try `composer install --no-scripts` this should prevent the post-install-cmd from running and let you update/install your packages
